In [14]:
from sklearn.preprocessing import PolynomialFeatures, OneHotEncoder
import numpy as np

X_num = [[3],[1],[0],[2],[4],[2]]
X_cat = [[2,'S'],[1,'F'],[1,'S'],[1,'D'],[2,'D'],[1,'F']]

poly = PolynomialFeatures(2)
Xp = poly.fit_transform(X_num)

enc = OneHotEncoder(sparse = False)
Xe = enc.fit_transform(X_cat)

X_preprocessed = np.hstack((Xp, Xe))


print('X_preprocessed', X_preprocessed)
print('X_cat:', X_cat)


X_preprocessed [[ 1.  3.  9.  0.  1.  0.  0.  1.]
 [ 1.  1.  1.  1.  0.  0.  1.  0.]
 [ 1.  0.  0.  1.  0.  0.  0.  1.]
 [ 1.  2.  4.  1.  0.  1.  0.  0.]
 [ 1.  4. 16.  0.  1.  1.  0.  0.]
 [ 1.  2.  4.  1.  0.  0.  1.  0.]]
X_cat: [[2, 'S'], [1, 'F'], [1, 'S'], [1, 'D'], [2, 'D'], [1, 'F']]
