## Homework 01 Supplement


### Part 1: List Implementation

The cells below provide an example of how to use the `insert` method of a list to insert a 1 at the beginning of each of the rows in `X`. Note that we create a copy of each row before we insert the 1, since we do not actually want to change the contents of the original matrix. 

In [1]:
X = [[9, 3, 6, 8, 7], [5, 2, 3, 1, 8], [4, 6, 2, 5, 1]]

for i in range(0, len(X)):
    row = X[i].copy()
    row.insert(0, 1)
    print(row)
    

[1, 9, 3, 6, 8, 7]
[1, 5, 2, 3, 1, 8]
[1, 4, 6, 2, 5, 1]


The code in the following cell performs the same function as the previous cell. It just uses a different style for writing the for loop.

In [2]:
X = [[9, 3, 6, 8, 7], [5, 2, 3, 1, 8], [4, 6, 2, 5, 1]]

for row in X:
    row_copy = row.copy()
    row_copy.insert(0, 1)
    print(row_copy)

[1, 9, 3, 6, 8, 7]
[1, 5, 2, 3, 1, 8]
[1, 4, 6, 2, 5, 1]


The cell below contains pseudocode for the `predict1` function.

The cell below contains pseudocode for the `sse1` function.

### Part 2: Array Implementation

In [3]:
import numpy as np

The cell below creates NumPy arrays from the list `X` in Part 1. 

In [4]:
X_array = np.array(X)

We can create a copy of `X_array` and add a column of ones to the front of the array as follows:

In [5]:
X_copy = X_array.copy()
ones = np.ones((X_array.shape[0], 1))
X_copy = np.hstack((ones, X_copy))

print(X_copy)

[[1. 9. 3. 6. 8. 7.]
 [1. 5. 2. 3. 1. 8.]
 [1. 4. 6. 2. 5. 1.]]


Assume that `X` represents a feature array for a regression problem, and we wish to find the `y_hat` values resulting from a regression model with coefficients given by `beta = np.array([2.4, 0.1, -0.4, 0.3, 0.2, -0.7])`. We can do so using matrix multiplication as shown below. Note that we need to take the transpose of `beta`. 

In [6]:
beta = np.array([2.4, 0.1, -0.4, 0.3, 0.2, -0.7])

y_hat = np.dot(X_copy, beta.reshape(-1, 1))
y_hat = y_hat.reshape(-1,)

print(y_hat)

[ 0.6 -2.4  1.3]


The cell below contains pseudocode for the `predict1` function.

The cell below contains pseudocode for the `predict1` function.